force-app/main/default/objects/Account/fields/Chiffre_d_affaire__c.field-meta.xml
<CustomField>
    <fullName>Chiffre_d_affaire__c</fullName>
    <label>Chiffre d affaire</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/ImportStatus__c.field-meta.xml
<CustomField>
    <defaultValue>"NotImported"</defaultValue>
    <fullName>ImportStatus__c</fullName>
    <label>Import Status</label>
    <type>Text</type>
    <length>20</length>
</CustomField>

force-app/main/default/classes/UpdateAccountsBatch.cls
global class UpdateAccountsBatch implements Database.Batchable<sObject>{
    
   global Database.QueryLocator start(Database.BatchableContext bc){ 
       //Requeter seulement les comptes qui ont au moins une commande avec le Status 'Ordered'
       return Database.getQueryLocator('SELECT Id, Chiffre_d_affaire__c FROM Account WHERE ImportStatus__c=\'AccountImported\'');

   }
    
   global void execute(Database.BatchableContext bc, List<Account> scope){      

       list<Aggregate> listOrders =  [SELECT Id, TotalAmount, AccountId FROM Order];
       
		for(integer i=0; i < scope.size(); i++){
			Account myAccount = scope[i];
			myAccount.Chiffre_d_affaire__c = 0;
           for(integer j=0; j < listOrders.size(); j++){
               if(listOrders[j].AccountId == myAccount.Id){
                   myAccount.Chiffre_d_affaire__c = myAccount.Chiffre_d_affaire__c + listOrders[j].TotalAmount;
               }                   
           }
       }
       
       update scope;
   }    
    
   global void finish(Database.BatchableContext info){     
       
   } 
}